baseurl = "http://localhost:1313"
languageCode = "en-gb"
title = "hhemanth.com"
theme = "hpstr"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 5
disqusShortname = "hpstrhugo"

[params]
	subtitle = "Ruby, Rails and related stuff"
	[params.author]
		name = "Hemanth Haridas"
		avatar = "/images/avatar.jpg"
		bio = "Engineer, Enterpreneur, Author"
		github = "hhemanth"
	[params.image]
	  feature = "/images/abstract-1.jpg"
	  credit = "dargadgetz"
	  creditlink = "http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/"
